# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1350fdcd24a6b803e0f1f3364e1e5de6376a4a726dfae65dd3abb4641f0e2c973ccbda1ab382bc8c78afc50b48e735681f5dd99e7fba35d58eeb41534db71591

test:
  secret_key_base: 939507798dc7afedc0afbcc427914f3b0e573649dd6050b00683fb2dfddd64d69960fb66b05c61a4834a9f5c4b00d7ae9b21eec4e3de0d15f5d8f50e7c28bb4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
